version: '3'
services:
  gateway:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - backend
  backend:
    build:
      dockerfile: ./Dockerfile
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
